### ISSUE TITLE
Python3.7. asyncio.async() function is deprecated, use ensure_future()

### ISSUE THREAD

**Issue by andrewmaximoff** [rethinkdb/rethinkdb-python#158]
Python3.7 don't support asyncio.async() need replace with a asyncio.ensure_future().
https://github.com/rethinkdb/rethinkdb/blob/d602ca096da20c136a90d0eb6fa0ad0622a87d86/drivers/python/rethinkdb/asyncio_net/net_asyncio.py#L136

**Comment by gabor-boros** [comment]
Hello @andrewmaximoff,
Thank you for letting us know! Now I moved this issue to the python driver's repo and I'll fix this issue during this week for the separate repo too. @JrooTJunior I'll upload this to PyPI around Friday due to I would like to fix other issues as well. Please note that the Python Drivers' 2.4.x versions are compatible with rethinkdb 2.4.x (which will be out soon)

**Comment by gabor-boros** [comment]
This issue is fixed within the python driver.
