### ISSUE TITLE
Query hangs when connection established on different asyncio loop

### ISSUE THREAD

**Issue by MarkDunne** [rethinkdb/rethinkdb-python#216]
**Describe the bug**
RethinkDB Query hangs when connection established on different asyncio loop

**To Reproduce**

```
import asyncio

from rethinkdb import RethinkDB

rethink = RethinkDB()
rethink.set_loop_type('asyncio')
rethink_conn = None


async def make_connection():
    global rethink_conn
    rethink_conn = await rethink.connect("localhost", 28015)


async def test_connection():
    print(await rethink.db_list().run(rethink_conn))
    await rethink_conn.close()


asyncio.get_event_loop().run_until_complete(make_connection())

# THIS WORKS
# asyncio.get_event_loop().run_until_complete(test_connection())

# THIS HANGS
asyncio.run(test_connection())
```

**Expected behavior**
The connection should work across loops, or fail with something rather than hanging

**System info**
 - RethinkDB Version:2.4.7

**Comment by lsabi** [comment]
Which python version are you using? If you're using python < 3.7, then it should not be working by design of python.

Also, would you mind trying the following option an see if it hangs?

```
asyncio.set_event_loop(async.get_event_loop())
asyncio.run(test_connection())
```

**Comment by MarkDunne** [comment]
I am using python Python 3.8.2.

Unfortunately, your snippet also hangs.

**Comment by lsabi** [comment]
Then the problem is in the `asyncio.run(test_connection())` piece of code.

I'm not sure if this can be captured by the library or if it is a language related problem. I'll give it a look, but I'm not sure there is a possible fix.

**For those who are having the same issue**, mind that `asyncio.run()` creates a new event loop, while `asyncio.run_until_complete()` uses the current event loop, although it is not possible to share objects across event loops.

**Comment by lsabi** [comment]
A possible solution could be to store a reference of the event loop used for instantiating the driver and then perform a check when running a coroutine, verifying that the current event loop is the same as the starting one.

The problem here is that the library would have to perform a check in every possible function/coroutine. As a result, this will seriously affect the performances.

As a suggestion, I would say to leave it to the user and document it properly, unless another solution arises, which does not affect the performance so heavily.

@gabor-boros what do you think?

**Comment by gabor-boros** [comment]
@lsabi thanks for Pinging me about this.

I didn't know much about this, but I'll try to look into this soon too. (This weekend or by Tuesday)

Until that I'll try to bring some ideas to the table around this.

To be honest the client would need a great refactor as discussed previously. (Regardless of this issue)

**Comment by gabor-boros** [comment]
So I checked this. I did not find a solution yet so I'll take one more look on this later next days. My assumption is that connection object cannot be passed across threads. I mean it can be, but the process will hang forever.

I'll try to check how could we solve to be able to pass the connection object.

**Off topic**

Generally speaking using shared objects instead of globals is always a better idea. The following piece of code **STILL NOT WORKS**, but at least using some context objects over globals.

```python
import asyncio

from rethinkdb import RethinkDB


class Context:
    connection = None


async def make_connection(ctx: Context):
    print(f"make conn :: thread-{asyncio.get_event_loop()._thread_id}")
    ctx.connection = await rethink.connect("localhost", 28015)


async def test_connection(ctx: Context):
    print(f"test conn :: thread-{asyncio.get_event_loop()._thread_id}")
    print(await rethink.db_list().run(ctx.connection))
    await rethink_conn.close()


if __name__ == "__main__":
    rethink = RethinkDB()
    rethink.set_loop_type('asyncio')
    
    context = Context()

    asyncio.get_event_loop().run_until_complete(make_connection(context))
    asyncio.run(test_connection(context))
```

**Comment by lsabi** [comment]
Thanks @gabor-boros for tuning in.

I also did some further research and it appears that it is not possible to share the object, as you said, but this should be outside the library's reach. I guess this is more of a python problem.

The thread is started with the code, but my guess is that it crashes, the thread keeps running, waiting for a response, which never arrives. Basically it becomes a deadlock that we cannot control.

I'm not sure if this is an issue that we can address or if we shall talk with the devs of python itself

**Comment by gabor-boros** [comment]
I thought about the same just wanted to validate somehow.

**Comment by dpineiden** [comment]
Hi.

The asyncio module provides to you an UNIQUE loop by thread. So if you want to run the new or the second loop you have to cancel or finish the first.
That issue is not an issue, is a matter of understanding how asyncio works.
If you need to run on the same process both functions, you have to declare first as future tasks, then load on the loop and run. 
Or using multiprccessing, create a new process and on this new process create a new loop

**Comment by dpineiden** [comment]
You could check this module that i created, on the test examples, you can see how work with asyncio:

https://gitlab.com/pineiden/datadbs-rethinkdb

**Comment by lsabi** [comment]
@dpineiden Thanks for jumping in. I'm not much knowledgeable about building asyncio libraries, so wasn't 100% sure.

I guess this is issue can be closed and the "bug" label be removed as this is definitely not a rethinkdb python driver's issue, but the way asyncio itself works.
