### ISSUE TITLE
Set loop type back to synchronous in set_loop_type

### ISSUE THREAD

**Issue by pashazz** [rethinkdb/rethinkdb-python#83]
So, after I do r.set_loop_type('asyncio') the returning value from r.connect changes to asyncio Future. But what if I want to use normal version of r.connect in some threads that are lacking an asyncio loop? Right now it leads to some consequences - 'generator' objects in unexpected places.

**Comment by mehaase** [comment]
I'm late to comment on this, but the `set_loop_type()` API is inherently dangerous. This issue is a good example of why: one part of the code changes some global state in the library that affects other parts of the code. It's not good encapsulation. It would be better to import directly from the appropriate module.

I.e. instead of:

```python
from rethinkdb import RethinkDB
r = RethinkDB()
r.set_loop_type('asyncio')
```

We should encourage this:

```python
from rethinkdb.net import AsyncioRethinkDB()
r = AsyncioRethinkDB()
```

This change would also allow different net drivers to offer slightly different APIs that are appropriate for their respective I/O frameworks. For example, the Trio driver uses "nurseries" which are basically task supervisors. Right now, there's a mess of monkey patching and weird import magic, but Python's normal import system is simple and clear. (And the commit that fixes this issue breaks the Trio driver.)

(I'm also not sure why the package was refactored to have a top level `RethinkDB` class. It seems to be a class that acts like a module? If the purpose of this class was to clean up handling of `set_loop_type`, then fixing `set_loop_type` would also let us get rid of this class, too.)

What do you think @gabor-boros and @grandquista?

**Comment by gabor-boros** [comment]
@mehaase I reopened this issue (not to forget) but I’ll only check it tomorrow

**Comment by grandquista** [comment]
The fix was to encapsulate, and no longer modify global state. `set_loop_type` is now modifying only the driver object instance state.

The refactor was not motivated by this method, and it made fixing the bug in `set_loop_type` possible.

The refactor was largely motivated by the tight coupling of the modules and circular imports making maintenance difficult. There were always classes acting like modules before and after.

> from rethinkdb.net import AsyncioRethinkDB
r = AsyncioRethinkDB()

wouldn't be impossible to implement. The problem right now, is that the driver is not connection centric. Queries are PoD objects and are decoupled from any connection or cursor. This does lead to some interesting implicit relationships. The Trio connect was broken recently by changing `set_loop_type`. This was a miss on our part looking at the new expected connection internal interface. Making the driver connection centric would fix this and allow the connections to only agree on a common public interface.

**Comment by gabor-boros** [comment]
@pashazz @mehaase @grandquista Should I close this?

**Comment by gabor-boros** [comment]
Closing the issue based on @grandquista comment due to inactivity.
